"""Mock Git/PR layer.

Applies a proposed patch to a local test repo clone, runs the test suite
against the patched code, generates a mock pull request object, and
persists it as a JSON artifact.
"""

from __future__ import annotations

import dataclasses
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import textwrap
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from ci_triage_agent.agent import FixSuggestion
from ci_triage_agent.parser import ParsedFailure


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class TestRunResult:
    """Summary of running the test suite against patched code."""

    # Whether the test runner exited with code 0
    passed: bool

    # Return code from pytest / the runner
    returncode: int

    # Captured stdout from the test runner
    stdout: str

    # Captured stderr from the test runner
    stderr: str

    # Number of tests collected / passed / failed (best-effort parse)
    tests_collected: int = 0
    tests_passed: int = 0
    tests_failed: int = 0

    @property
    def combined_output(self) -> str:
        return (self.stdout + "\n" + self.stderr).strip()


@dataclass
class MockPullRequest:
    """A mock pull request generated by the CI triage agent."""

    # Unique identifier for this PR
    pr_id: str

    # Human-readable title
    title: str

    # Branch name that the patch would live on
    branch_name: str

    # The unified diff of all changes
    diff: str

    # Files changed by the patch
    changed_files: list[str]

    # Test run result after applying the patch
    test_result: TestRunResult

    # The parsed failure that triggered this PR
    parsed_failure: ParsedFailure

    # The fix suggestion that produced the patch
    fix_suggestion: FixSuggestion

    # Timestamp when the PR was created
    created_at: str = field(
        default_factory=lambda: datetime.now(tz=timezone.utc).isoformat()
    )

    # Arbitrary labels/tags
    labels: list[str] = field(default_factory=list)

    # Path to the persisted JSON artifact (set after calling .save())
    artifact_path: str = ""

    # Whether the patch applied cleanly
    patch_applied: bool = True

    # Any error that occurred during patch application / test run
    error: Optional[str] = None

    @property
    def status(self) -> str:
        """High-level status string."""
        if self.error:
            return "error"
        if not self.patch_applied:
            return "patch_failed"
        if self.test_result.passed:
            return "tests_pass"
        return "tests_fail"

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-safe dictionary."""
        return {
            "schema_version": "1.0",
            "pr_id": self.pr_id,
            "title": self.title,
            "branch_name": self.branch_name,
            "diff": self.diff,
            "changed_files": self.changed_files,
            "status": self.status,
            "patch_applied": self.patch_applied,
            "created_at": self.created_at,
            "labels": self.labels,
            "artifact_path": self.artifact_path,
            "error": self.error,
            "test_result": {
                "passed": self.test_result.passed,
                "returncode": self.test_result.returncode,
                "stdout": self.test_result.stdout,
                "stderr": self.test_result.stderr,
                "tests_collected": self.test_result.tests_collected,
                "tests_passed": self.test_result.tests_passed,
                "tests_failed": self.test_result.tests_failed,
            },
            "fix_suggestion": {
                "explanation": self.fix_suggestion.explanation,
                "patch": self.fix_suggestion.patch,
                "target_file": self.fix_suggestion.target_file,
                "model": self.fix_suggestion.model,
                "used_mock": self.fix_suggestion.used_mock,
                "has_patch": self.fix_suggestion.has_patch,
                "agent_error": self.fix_suggestion.agent_error,
            },
            "parsed_failure": {
                "run_id": self.parsed_failure.run_id,
                "failure_type": self.parsed_failure.failure_type.value,
                "error_file": self.parsed_failure.error_file,
                "error_line": self.parsed_failure.error_line,
                "error_message": self.parsed_failure.error_message,
                "test_name": self.parsed_failure.test_name,
                "source_file": self.parsed_failure.source_file,
            },
        }

    def save(self, output_dir: str | Path = ".") -> Path:
        """Persist this PR as a JSON artifact and return the path."""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        filename = f"pr_{self.pr_id[:8]}.json"
        dest = output_dir / filename
        dest.write_text(json.dumps(self.to_dict(), indent=2), encoding="utf-8")
        self.artifact_path = str(dest)
        return dest


# ---------------------------------------------------------------------------
# Repo scaffold helpers
# ---------------------------------------------------------------------------

def _scaffold_test_repo(sandbox: Path, failure: ParsedFailure) -> None:
    """Create a minimal Python project structure inside *sandbox*."""
    # Create directory layout mirroring the error file
    error_file_path = Path(failure.error_file)
    target = sandbox / error_file_path
    target.parent.mkdir(parents=True, exist_ok=True)

    # Write a stub source file that contains the "broken" code.
    # We derive broken content from snippet / raw_metadata.
    snippet = failure.snippet or failure.raw_metadata.get("snippet") or ""
    broken_code = _build_broken_source(failure, snippet)
    target.write_text(broken_code, encoding="utf-8")

    # Create a minimal tests directory with a trivial passing test so that
    # pytest can at least discover something.
    tests_dir = sandbox / "tests"
    tests_dir.mkdir(exist_ok=True)
    (tests_dir / "__init__.py").write_text("", encoding="utf-8")
    (tests_dir / "test_smoke.py").write_text(
        textwrap.dedent("""\
            # Smoke test – always passes after patch.
            def test_smoke():
                assert True
        """),
        encoding="utf-8",
    )

    # Minimal pyproject.toml so pytest finds the project
    (sandbox / "pyproject.toml").write_text(
        textwrap.dedent("""\
            [build-system]
            requires = ["setuptools"]
            build-backend = "setuptools.build_meta"

            [project]
            name = "sandbox-project"
            version = "0.0.1"
        """),
        encoding="utf-8",
    )


def _build_broken_source(failure: ParsedFailure, snippet: str) -> str:
    """Build stub Python source that represents the pre-patch (broken) state."""
    from ci_triage_agent.parser import FailureType

    ft = failure.failure_type
    lines: list[str] = [f"# Stub source file for: {failure.error_file}"]

    if ft == FailureType.SYNTAX_ERROR:
        # Embed the broken snippet verbatim so the file truly has a syntax error;
        # but we need the REST of the file to be valid so we wrap in a string.
        # Actually – we want a parseable file with a known bad line so the patch
        # can flip it.  We use a comment showing the broken line and a valid stand-in.
        lines.append("")
        if snippet:
            # Write a version without the trailing colon (broken), but still
            # parseable by wrapping in a pass block replaced by the snippet comment.
            lines.append(f"# BROKEN LINE: {snippet.strip()}")
            # Write a stub function that is intentionally missing its colon
            # We write it as a plain broken string so it's parseable as a module
            lines.append("def stub_function():  # placeholder")
            lines.append("    pass")
        else:
            lines.append("def stub_function():  # placeholder")
            lines.append("    pass")

    elif ft == FailureType.IMPORT_ERROR:
        m = re.search(r"No module named '([^']+)'", failure.error_message)
        module = m.group(1) if m else "unknown_module"
        lines.append(f"# This import will fail: {failure.error_message}")
        lines.append(f"# import {module}  # commented out so file is parseable")
        lines.append("")
        lines.append("def main():")
        lines.append("    pass")

    elif ft == FailureType.TEST_FAILURE:
        test_name = failure.test_name or "test_stub"
        lines.append("")
        lines.append(f"def {test_name}():")
        lines.append(f"    # Original failing assertion: {failure.error_message}")
        lines.append("    assert False, 'stub failing test'")

    elif ft == FailureType.LINT_ERROR:
        if "E501" in failure.error_message:
            long_line = "x = '" + "a" * 200 + "'"
            lines.append("")
            lines.append(long_line)
        elif "F401" in failure.error_message:
            m = re.search(r"'([^']+)' imported but unused", failure.error_message)
            module = m.group(1) if m else "os"
            lines.append(f"import {module}")
            lines.append("")
            lines.append("def main():")
            lines.append("    pass")
        else:
            lines.append("")
            lines.append("pass")
    else:
        lines.append("pass")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Patch application
# ---------------------------------------------------------------------------

def _apply_patch(sandbox: Path, patch_text: str) -> tuple[bool, str]:
    """Apply a unified diff patch inside *sandbox*.

    Returns
    -------
    (success, error_message)
    """
    if not patch_text.strip():
        return False, "Empty patch – nothing to apply."

    # Write patch to a temp file
    patch_file = sandbox / "proposed.patch"
    patch_file.write_text(patch_text, encoding="utf-8")

    # Try GNU patch first, then fall back to Python-based application
    patch_cmd = shutil.which("patch")
    if patch_cmd:
        result = subprocess.run(
            [patch_cmd, "-p1", "--input", str(patch_file), "--directory", str(sandbox)],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return True, ""
        # If GNU patch fails, fall through to our Python implementation

    # Python-based patch application
    return _apply_patch_python(sandbox, patch_text)


def _apply_patch_python(sandbox: Path, patch_text: str) -> tuple[bool, str]:
    """Pure-Python unified diff applier (handles a/b/ prefixes)."""
    try:
        hunks = _parse_unified_diff(patch_text)
        if not hunks:
            return False, "Could not parse any hunks from the patch."
        for filepath, file_hunks in hunks.items():
            _apply_file_hunks(sandbox, filepath, file_hunks)
        return True, ""
    except Exception as exc:  # noqa: BLE001
        return False, str(exc)


def _parse_unified_diff(
    patch_text: str,
) -> dict[str, list[list[str]]]:
    """Parse a unified diff into {filepath: [hunk_lines]} mapping."""
    result: dict[str, list[list[str]]] = {}
    current_file: str | None = None
    current_hunk: list[str] = []

    for line in patch_text.splitlines():
        if line.startswith("+++ "):
            # Extract file path, strip b/ prefix
            raw = line[4:].strip()
            filepath = re.sub(r"^b/", "", raw)
            current_file = filepath
            if current_file not in result:
                result[current_file] = []
            current_hunk = []
        elif line.startswith("--- "):
            continue  # skip source file line
        elif line.startswith("@@ "):
            if current_file is not None and current_hunk:
                result[current_file].append(current_hunk)
            current_hunk = []
        elif current_file is not None:
            current_hunk.append(line)

    if current_file is not None and current_hunk:
        result[current_file].append(current_hunk)

    return result


def _apply_file_hunks(
    sandbox: Path,
    filepath: str,
    hunks: list[list[str]],
) -> None:
    """Apply hunks to a file inside sandbox, creating it if necessary."""
    target = sandbox / filepath
    target.parent.mkdir(parents=True, exist_ok=True)

    if target.exists():
        original_lines = target.read_text(encoding="utf-8").splitlines(keepends=True)
    else:
        original_lines = []

    result_lines = list(original_lines)

    # Process hunks by applying deletions/additions
    for hunk in hunks:
        new_result: list[str] = []
        hunk_idx = 0
        original_idx = 0

        # Simple approach: remove '-' lines and add '+' lines
        lines_to_remove = [l[1:] for l in hunk if l.startswith("-")]
        lines_to_add = [l[1:] for l in hunk if l.startswith("+")]
        context_lines = [l[1:] for l in hunk if l.startswith(" ")]

        # Build new file content by replacing removed lines with added lines
        result_text = "".join(result_lines)
        for rem in lines_to_remove:
            result_text = result_text.replace(rem.rstrip("\n"), "<<<REMOVE>>>", 1)
        # Remove the placeholders
        result_lines_new = []
        for l in result_text.splitlines(keepends=True):
            if l.rstrip("\n") == "<<<REMOVE>>>":
                continue
            result_lines_new.append(l)

        # Insert added lines at the position of the first removal or at end
        if lines_to_add:
            # Find insertion point (after context / removals)
            # Simple: append at end if we can't find context
            insert_done = False
            if context_lines:
                ctx_text = context_lines[0].rstrip("\n")
                for i, l in enumerate(result_lines_new):
                    if l.rstrip("\n") == ctx_text:
                        for j, add_line in enumerate(lines_to_add):
                            new_line = add_line if add_line.endswith("\n") else add_line + "\n"
                            result_lines_new.insert(i + 1 + j, new_line)
                        insert_done = True
                        break
            if not insert_done:
                for add_line in lines_to_add:
                    new_line = add_line if add_line.endswith("\n") else add_line + "\n"
                    result_lines_new.append(new_line)

        result_lines = result_lines_new

    target.write_text("".join(result_lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Test runner
# ---------------------------------------------------------------------------

def _run_tests(sandbox: Path, timeout: int = 60) -> TestRunResult:
    """Run pytest inside *sandbox* and return a TestRunResult."""
    result = subprocess.run(
        [
            sys.executable, "-m", "pytest",
            str(sandbox / "tests"),
            "-x", "-q", "--tb=short",
            "--no-header",
        ],
        capture_output=True,
        text=True,
        timeout=timeout,
        cwd=str(sandbox),
    )
    stdout = result.stdout
    stderr = result.stderr
    passed = result.returncode == 0

    # Parse pytest summary line: "N passed", "N failed", etc.
    collected = 0
    n_passed = 0
    n_failed = 0

    collected_m = re.search(r"(\d+) (?:test[s]? )?(?:collected|selected)", stdout)
    if collected_m:
        collected = int(collected_m.group(1))

    passed_m = re.search(r"(\d+) passed", stdout)
    if passed_m:
        n_passed = int(passed_m.group(1))

    failed_m = re.search(r"(\d+) failed", stdout)
    if failed_m:
        n_failed = int(failed_m.group(1))

    if collected == 0 and n_passed:
        collected = n_passed + n_failed

    return TestRunResult(
        passed=passed,
        returncode=result.returncode,
        stdout=stdout,
        stderr=stderr,
        tests_collected=collected,
        tests_passed=n_passed,
        tests_failed=n_failed,
    )


# ---------------------------------------------------------------------------
# Branch name helper
# ---------------------------------------------------------------------------

def _make_branch_name(failure: ParsedFailure, pr_id: str) -> str:
    """Generate a git-safe branch name for the PR."""
    ft = failure.failure_type.value
    # Sanitise the error file path to be branch-name safe
    safe_file = re.sub(r"[^a-zA-Z0-9_-]", "-", failure.error_file)
    safe_file = re.sub(r"-+", "-", safe_file).strip("-")[:40]
    short_id = pr_id[:8]
    return f"ci-triage/{ft}/{safe_file}/{short_id}"


def _make_pr_title(failure: ParsedFailure) -> str:
    """Generate a human-readable PR title."""
    ft = failure.failure_type.value.replace("_", " ").title()
    short_msg = failure.error_message[:60].rstrip()
    return f"fix({ft}): {short_msg} in {failure.error_file}"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

class GitPRLayer:
    """Manages the mock Git/PR workflow for applying and testing patches.

    Parameters
    ----------
    output_dir:
        Directory where PR JSON artifacts are saved.
    test_timeout:
        Seconds to allow the test suite to run.
    """

    def __init__(
        self,
        output_dir: str | Path = "pr_artifacts",
        test_timeout: int = 60,
    ) -> None:
        self.output_dir = Path(output_dir)
        self.test_timeout = test_timeout

    def create_pull_request(
        self,
        suggestion: FixSuggestion,
    ) -> MockPullRequest:
        """Apply the patch from *suggestion*, run tests, and return a MockPullRequest.

        The workflow is:
        1. Create a temporary sandbox directory with a minimal repo structure.
        2. Apply the proposed unified diff.
        3. Run the test suite inside the sandbox.
        4. Assemble and persist a MockPullRequest artifact.

        Parameters
        ----------
        suggestion:
            A FixSuggestion from the agent layer.

        Returns
        -------
        MockPullRequest
            Always returns a PR object; errors are captured in ``.error``.
        """
        pr_id = str(uuid.uuid4())
        failure = suggestion.parsed_failure

        with tempfile.TemporaryDirectory(prefix="ci_triage_pr_") as tmpdir:
            sandbox = Path(tmpdir)
            try:
                return self._build_pr(suggestion, failure, pr_id, sandbox)
            except Exception as exc:  # noqa: BLE001
                # Build a minimal PR with the error recorded
                empty_test = TestRunResult(
                    passed=False,
                    returncode=-1,
                    stdout="",
                    stderr="",
                )
                pr = MockPullRequest(
                    pr_id=pr_id,
                    title=_make_pr_title(failure),
                    branch_name=_make_branch_name(failure, pr_id),
                    diff=suggestion.patch,
                    changed_files=[failure.error_file],
                    test_result=empty_test,
                    parsed_failure=failure,
                    fix_suggestion=suggestion,
                    patch_applied=False,
                    error=str(exc),
                    labels=["error"],
                )
                pr.save(self.output_dir)
                return pr

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _build_pr(
        self,
        suggestion: FixSuggestion,
        failure: ParsedFailure,
        pr_id: str,
        sandbox: Path,
    ) -> MockPullRequest:
        # 1. Scaffold repo
        _scaffold_test_repo(sandbox, failure)

        # 2. Apply patch
        patch_applied = False
        patch_error: Optional[str] = None
        diff_used = suggestion.patch

        if suggestion.has_patch:
            ok, err = _apply_patch(sandbox, suggestion.patch)
            patch_applied = ok
            if not ok:
                patch_error = err
        else:
            patch_error = "No patch provided by the agent."

        # 3. Run tests (always, even if patch failed – smoke tests may still pass)
        test_result = _run_tests(sandbox, timeout=self.test_timeout)

        # 4. Determine changed files from the diff
        changed_files = _extract_changed_files(suggestion.patch)
        if not changed_files:
            changed_files = [failure.error_file] if failure.error_file else []

        # 5. Labels
        labels: list[str] = [failure.failure_type.value]
        if suggestion.used_mock:
            labels.append("mock-llm")
        if test_result.passed:
            labels.append("tests-pass")
        else:
            labels.append("tests-fail")

        # 6. Assemble PR
        pr = MockPullRequest(
            pr_id=pr_id,
            title=_make_pr_title(failure),
            branch_name=_make_branch_name(failure, pr_id),
            diff=diff_used,
            changed_files=changed_files,
            test_result=test_result,
            parsed_failure=failure,
            fix_suggestion=suggestion,
            patch_applied=patch_applied,
            error=patch_error if not patch_applied else None,
            labels=labels,
        )

        # 7. Persist
        pr.save(self.output_dir)
        return pr


def _extract_changed_files(patch_text: str) -> list[str]:
    """Extract the list of target files mentioned in a unified diff."""
    files: list[str] = []
    for line in patch_text.splitlines():
        if line.startswith("+++ "):
            raw = line[4:].strip()
            filepath = re.sub(r"^b/", "", raw)
            if filepath and filepath != "/dev/null":
                files.append(filepath)
    return list(dict.fromkeys(files))  # deduplicate, preserve order


def create_pull_request(
    suggestion: FixSuggestion,
    output_dir: str | Path = "pr_artifacts",
    test_timeout: int = 60,
) -> MockPullRequest:
    """Convenience wrapper around :class:`GitPRLayer`."""
    layer = GitPRLayer(output_dir=output_dir, test_timeout=test_timeout)
    return layer.create_pull_request(suggestion)
